name: cnn_quantization_tf_seismic
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.2
  - pip
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - matplotlib=3.10.1
  - seaborn=0.13.2
  - pillow=11.1.0
  - pyyaml=6.0.2
  - tqdm=4.67.1
  - requests=2.32.3
  - h5py=3.14.0
  - pip:
    - tensorflow==2.20.0
    - tensorflow-model-optimization==0.8.0
    - keras==3.11.3
    - torch==2.6.0
    - torchvision==0.21.0
    - torchmetrics==1.6.2
    - transformers==4.49.0
    - datasets==3.3.2
    - huggingface-hub==0.29.3
    - timm==1.0.15
    - shap==0.47.2
    - xgboost==3.0.0
    - numba==0.61.2
    - einops==0.8.1
    - lightning-utilities==0.14.0
    - triton==3.2.0
    - nvidia-cublas-cu12==12.9.1.4
    - nvidia-cuda-cupti-cu12==12.9.79
    - nvidia-cuda-nvcc-cu12==12.9.86
    - nvidia-cuda-nvrtc-cu12==12.9.86
    - nvidia-cuda-runtime-cu12==12.9.79
    - nvidia-cudnn-cu12==9.13.0.50
    - nvidia-cufft-cu12==11.4.1.4
    - nvidia-curand-cu12==10.3.10.19
    - nvidia-cusolver-cu12==11.7.5.82
    - nvidia-cusparse-cu12==12.5.10.65
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-nccl-cu12==2.28.3
    - nvidia-nvjitlink-cu12==12.9.86
    - nvidia-nvtx-cu12==12.4.127
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - absl-py==1.4.0
    - astunparse==1.6.3
    - dm-tree==0.1.8
    - flatbuffers==25.2.10
    - gast==0.6.0
    - google-pasta==0.2.0
    - grpcio==1.71.0
    - libclang==18.1.1
    - ml-dtypes==0.5.3
    - namex==0.1.0
    - opt-einsum==3.4.0
    - optree==0.17.0
    - protobuf==6.30.0
    - termcolor==3.1.0
    - wrapt==1.17.3
    - cloudpickle==3.1.1
    - dill==0.3.8
    - fsspec==2025.3.0
    - joblib==1.4.2
    - threadpoolctl==3.5.0
    - slicer==0.0.8
    - mpmath==1.3.0
    - sympy==1.13.1
    - networkx==3.4.2
    - llvmlite==0.44.0
    - markdown==3.7
    - markdown-it-py==4.0.0
    - mdurl==0.1.2
    - rich==14.1.0
    - jinja2==3.1.6
    - markupsafe==3.0.2
    - werkzeug==3.1.3
    - charset-normalizer==3.4.1
    - idna==3.10
    - urllib3==2.3.0
    - certifi==2025.1.31
    - fonttools==4.56.0
    - kiwisolver==1.4.8
    - pyparsing==3.2.1
    - cycler==0.12.1
    - six==1.17.0
