vehicle_classification:
    class_names: ["background", "nissan", "lexus", "mazda", "benz"]
    included_classes: [ "background", "nissan","lexus", "mazda", "benz"]
    train_index_file: /home/tkimura4/data/datasets/2025-09-21-ICT/train_index.txt
    val_index_file: /home/tkimura4/data/datasets/2025-09-21-ICT/val_index.txt

max_distance_m: 15 # meters
